// Code generated by go-swagger; DO NOT EDIT.

package goods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
)

// AddGoodsToBasketHandlerFunc turns a function with the right signature into a add goods to basket handler
type AddGoodsToBasketHandlerFunc func(AddGoodsToBasketParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn AddGoodsToBasketHandlerFunc) Handle(params AddGoodsToBasketParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// AddGoodsToBasketHandler interface for that can handle valid add goods to basket params
type AddGoodsToBasketHandler interface {
	Handle(AddGoodsToBasketParams, interface{}) middleware.Responder
}

// NewAddGoodsToBasket creates a new http.Handler for the add goods to basket operation
func NewAddGoodsToBasket(ctx *middleware.Context, handler AddGoodsToBasketHandler) *AddGoodsToBasket {
	return &AddGoodsToBasket{Context: ctx, Handler: handler}
}

/*AddGoodsToBasket swagger:route POST /basket/{basketId}/goods goods addGoodsToBasket

change goods quantity in basket

*/
type AddGoodsToBasket struct {
	Context *middleware.Context
	Handler AddGoodsToBasketHandler
}

func (o *AddGoodsToBasket) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddGoodsToBasketParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// AddGoodsToBasketBody add goods to basket body
// swagger:model AddGoodsToBasketBody
type AddGoodsToBasketBody struct {

	// product Id
	ProductID int64 `json:"productId,omitempty"`

	// quantity
	Quantity int64 `json:"quantity,omitempty"`
}

// Validate validates this add goods to basket body
func (o *AddGoodsToBasketBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *AddGoodsToBasketBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AddGoodsToBasketBody) UnmarshalBinary(b []byte) error {
	var res AddGoodsToBasketBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
