// Code generated by go-swagger; DO NOT EDIT.

package goods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllGoodsInBasketHandlerFunc turns a function with the right signature into a get all goods in basket handler
type GetAllGoodsInBasketHandlerFunc func(GetAllGoodsInBasketParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllGoodsInBasketHandlerFunc) Handle(params GetAllGoodsInBasketParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAllGoodsInBasketHandler interface for that can handle valid get all goods in basket params
type GetAllGoodsInBasketHandler interface {
	Handle(GetAllGoodsInBasketParams, interface{}) middleware.Responder
}

// NewGetAllGoodsInBasket creates a new http.Handler for the get all goods in basket operation
func NewGetAllGoodsInBasket(ctx *middleware.Context, handler GetAllGoodsInBasketHandler) *GetAllGoodsInBasket {
	return &GetAllGoodsInBasket{Context: ctx, Handler: handler}
}

/*GetAllGoodsInBasket swagger:route GET /basket/{basketId}/goods goods getAllGoodsInBasket

return all goods in basket

*/
type GetAllGoodsInBasket struct {
	Context *middleware.Context
	Handler GetAllGoodsInBasketHandler
}

func (o *GetAllGoodsInBasket) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllGoodsInBasketParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
