// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// LoginUserOKCode is the HTTP code returned for type LoginUserOK
const LoginUserOKCode int = 200

/*LoginUserOK OK

swagger:response loginUserOK
*/
type LoginUserOK struct {
	/*token to pass in every request to user auth

	 */
	XAuthToken string `json:"X-Auth-Token"`
}

// NewLoginUserOK creates LoginUserOK with default headers values
func NewLoginUserOK() *LoginUserOK {

	return &LoginUserOK{}
}

// WithXAuthToken adds the xAuthToken to the login user o k response
func (o *LoginUserOK) WithXAuthToken(xAuthToken string) *LoginUserOK {
	o.XAuthToken = xAuthToken
	return o
}

// SetXAuthToken sets the xAuthToken to the login user o k response
func (o *LoginUserOK) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WriteResponse to the client
func (o *LoginUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Auth-Token

	xAuthToken := o.XAuthToken
	if xAuthToken != "" {
		rw.Header().Set("X-Auth-Token", xAuthToken)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// LoginUserUnauthorizedCode is the HTTP code returned for type LoginUserUnauthorized
const LoginUserUnauthorizedCode int = 401

/*LoginUserUnauthorized Invalid username/password supplied

swagger:response loginUserUnauthorized
*/
type LoginUserUnauthorized struct {
}

// NewLoginUserUnauthorized creates LoginUserUnauthorized with default headers values
func NewLoginUserUnauthorized() *LoginUserUnauthorized {

	return &LoginUserUnauthorized{}
}

// WriteResponse to the client
func (o *LoginUserUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
