// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi CityProject for Auchan
This is a server for collaborative shopping.



    Schemes:
      http
    Host: aeuchan.swagger.io
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
