// Code generated by go-swagger; DO NOT EDIT.

package share

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/itimofeev/auchan/server/models"
)

// GetAllSharesForBasketOKCode is the HTTP code returned for type GetAllSharesForBasketOK
const GetAllSharesForBasketOKCode int = 200

/*GetAllSharesForBasketOK returns created share

swagger:response getAllSharesForBasketOK
*/
type GetAllSharesForBasketOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Share `json:"body,omitempty"`
}

// NewGetAllSharesForBasketOK creates GetAllSharesForBasketOK with default headers values
func NewGetAllSharesForBasketOK() *GetAllSharesForBasketOK {

	return &GetAllSharesForBasketOK{}
}

// WithPayload adds the payload to the get all shares for basket o k response
func (o *GetAllSharesForBasketOK) WithPayload(payload []*models.Share) *GetAllSharesForBasketOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all shares for basket o k response
func (o *GetAllSharesForBasketOK) SetPayload(payload []*models.Share) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllSharesForBasketOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Share, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
