// Code generated by go-swagger; DO NOT EDIT.

package share

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllSharesForBasketHandlerFunc turns a function with the right signature into a get all shares for basket handler
type GetAllSharesForBasketHandlerFunc func(GetAllSharesForBasketParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllSharesForBasketHandlerFunc) Handle(params GetAllSharesForBasketParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAllSharesForBasketHandler interface for that can handle valid get all shares for basket params
type GetAllSharesForBasketHandler interface {
	Handle(GetAllSharesForBasketParams, interface{}) middleware.Responder
}

// NewGetAllSharesForBasket creates a new http.Handler for the get all shares for basket operation
func NewGetAllSharesForBasket(ctx *middleware.Context, handler GetAllSharesForBasketHandler) *GetAllSharesForBasket {
	return &GetAllSharesForBasket{Context: ctx, Handler: handler}
}

/*GetAllSharesForBasket swagger:route GET /basket/{basketId}/share share getAllSharesForBasket

get all shares for basket

*/
type GetAllSharesForBasket struct {
	Context *middleware.Context
	Handler GetAllSharesForBasketHandler
}

func (o *GetAllSharesForBasket) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllSharesForBasketParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
