// Code generated by go-swagger; DO NOT EDIT.

package basket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/itimofeev/auchan/server/models"
)

// CreateBasketOKCode is the HTTP code returned for type CreateBasketOK
const CreateBasketOKCode int = 200

/*CreateBasketOK successful operation

swagger:response createBasketOK
*/
type CreateBasketOK struct {

	/*
	  In: Body
	*/
	Payload *models.Basket `json:"body,omitempty"`
}

// NewCreateBasketOK creates CreateBasketOK with default headers values
func NewCreateBasketOK() *CreateBasketOK {

	return &CreateBasketOK{}
}

// WithPayload adds the payload to the create basket o k response
func (o *CreateBasketOK) WithPayload(payload *models.Basket) *CreateBasketOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create basket o k response
func (o *CreateBasketOK) SetPayload(payload *models.Basket) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBasketOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateBasketNotFoundCode is the HTTP code returned for type CreateBasketNotFound
const CreateBasketNotFoundCode int = 404

/*CreateBasketNotFound Not found

swagger:response createBasketNotFound
*/
type CreateBasketNotFound struct {
}

// NewCreateBasketNotFound creates CreateBasketNotFound with default headers values
func NewCreateBasketNotFound() *CreateBasketNotFound {

	return &CreateBasketNotFound{}
}

// WriteResponse to the client
func (o *CreateBasketNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
